=== oliviafabreschi/xml_course/assignments/schemaxml.xsd
<?xml version="1.0"?>
<!-- Filnamn: schemaxml.xsd -->
<!-- Författare: Olivia Fabreschi -->
<!-- Datum: 23 Mars 2024 -->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dictionary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="author" type="xs:string"/>
                <xs:element name="words">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="word" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <!-- Text-delen av varje word -->
                                        <xs:extension base="xs:string">
                                            <!-- specifierar nr för varje word för att senare lättare kunna översätta orden  -->
                                            <xs:attribute name="ID" type="xs:positiveInteger" use="required"/>
                                        </xs:extension>
                                     </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <!-- Specifierar att det måste vara mellan dessa språk -->
            <xs:attribute name="language">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Swedish"/>
                        <xs:enumeration value="French"/>
                        <xs:enumeration value="English"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== oliviafabreschi/xml_course/assignments/english.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheetxsl.xsl"?>
<!-- Filnamn: english.xml -->
<!-- Författare: Olivia Fabreschi -->
<!-- Datum: 23 Mars 2024 -->
<!-- CSS stylesheet-->
<!-- <?xml-stylesheet type="text/css" href="stylesheet.css" ?> -->
<!-- DTD schema-->
<!--<!DOCTYPE dictionary SYSTEM "dtdSchema.dtd" >-->
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemaxml.xsd" language="English">
    <!-- Engelsk ordbok -->
    <title>English Dictionary</title>
    <author>Olivia</author>
    <words>
        <!-- numrerar orden för att lättare kunna matcha de till de olika språken-->
        <word ID = "1">Cat</word>
        <word ID = "2">Dog</word>
        <word ID = "3">Hello</word>
        <word ID = "4">Goodbye</word>
        <word ID = "5">Red</word>
        <word ID = "6">Blue</word>
        <word ID = "7">House</word>
        <word ID = "8">Mug</word>
        <word ID = "9">Mountain</word>
        <word ID = "10">Think</word>
    </words>
</dictionary>

=== oliviafabreschi/xml_course/assignments/swedish.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheetxsl.xsl"?>
<!-- Filnamn: swedish.xml -->
<!-- Författare: Olivia Fabreschi -->
<!-- Datum: 23 Mars 2024 -->

<!-- CSS stylesheet-->
<!-- <?xml-stylesheet type="text/css" href="stylesheet.css" ?> -->
<!-- DTD schema-->
<!--<!DOCTYPE dictionary SYSTEM "dtdSchema.dtd" >-->
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemaxml.xsd" language="Swedish">
    <!-- svensk ordbok -->
    <title>Swedish Dictionary</title>
    <author>Olivia</author>
    <words>
        <!-- numrerar orden för att lättare kunna matcha de till de olika språken-->
        <word ID = "1">Katt</word>
        <word ID = "2">Hund</word>
        <word ID = "3">Hej</word>
        <word ID = "4">Hejdå</word>
        <word ID = "5">Röd</word>
        <word ID = "6">Blå</word>
        <word ID = "7">Hus</word>
        <word ID = "8">Mugg</word>
        <word ID = "9">Berg</word>
        <word ID = "10">Tänka</word>
    </words>
</dictionary>

=== oliviafabreschi/xml_course/assignments/french.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Filnamn: french.xml -->
<!-- Författare: Olivia Fabreschi -->
<!-- Datum: 23 Mars 2024 -->
<?xml-stylesheet type="text/css" href="stylesheet.css" ?>
<!DOCTYPE dictionary SYSTEM "/Users/oliviafabreschi/IdeaProjects/xml_course/assignments/dtdSchema.dtd" >
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemaxml.xsd" language="French">
    <!-- fransk ordbok -->
    <title>French Dictionary</title>
    <author>Olivia</author>
    <words>
        <!-- numrerar orden för att lättare kunna matcha de till de olika språken-->
        <word ID = "1">Chat</word>
        <word ID = "2">Chien</word>
        <word ID = "3">Salut</word>
        <word ID = "4">Aurevoir</word>
        <word ID = "5">Rouge</word>
        <word ID = "6">Bleu</word>
        <word ID = "7">Maison</word>
        <word ID = "8">Tasse</word>
        <word ID = "9">Montagne</word>
        <word ID = "10">Penser</word>
    </words>
</dictionary>
